version: '3.8'
services:
  webapp:
    image: 408918962370.dkr.ecr.us-east-1.amazonaws.com/pyhostname-ecr:latest
    container_name: pyhostname_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always