# .github/workflows/deploy.yml

name: '2. Deploy da Aplicação'

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
  workflow_dispatch:


jobs:  
  build-and-push:
    name: Construir e Enviar para ECR
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Mude para a sua região

      - name: Login no Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir e Enviar a imagem para o ECR        
        env:
          ECR_REPOSITORY_URL: ${{ secrets.ECR_REPOSITORY_URL }}
        run: |
          
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)        
          docker build -t $ECR_REPOSITORY_URL:$IMAGE_TAG -t $ECR_REPOSITORY_URL:latest ./app
          docker push $ECR_REPOSITORY_URL --all-tags