# .github/workflows/terraform.yml

name: 'Terraform Infrastructure Pipeline'

on:
  # O gatilho manual continua o mesmo
  workflow_dispatch:
    inputs:
      action:
        description: 'Apply (criar) ou Destroy (destruir)'
        required: true
        default: 'apply'
        type: choice
        options:
        - apply
        - destroy

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./infra/terraform

    steps:
      - name: 1. Checkout do Repositório
        uses: actions/checkout@v4

      - name: 2. Configurar Credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Mude para a sua região

      - name: 3. Setup do Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 4. Terraform Init
        run: terraform init

      - name: 5. Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve

      - name: 6. Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve